//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace endoDB.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("endoDB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Manager に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administration date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string admin_date {
            get {
                return ResourceManager.GetString("admin_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can final check に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string allow_fc {
            get {
                return ResourceManager.GetString("allow_fc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birthday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank is not allowed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BlankNotAllowed {
            get {
                return ResourceManager.GetString("BlankNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can not change ID. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotChangeId {
            get {
                return ResourceManager.GetString("CanNotChangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Category に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your changes have not been saved. Discard changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangesNotSavedDiscardOrNot {
            get {
                return ResourceManager.GetString("ChangesNotSavedDiscardOrNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All changes will be lost. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangesWillLost {
            get {
                return ResourceManager.GetString("ChangesWillLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Checker {
            get {
                return ResourceManager.GetString("Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click here to update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Click2Update {
            get {
                return ResourceManager.GetString("Click2Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click position where you want to insert this word on Purpose, Findings, Checker&apos;s comment, or Pathology. Then click the word again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClickInsPosition {
            get {
                return ResourceManager.GetString("ClickInsPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Comment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to change it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmChanging {
            get {
                return ResourceManager.GetString("ConfirmChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmDel {
            get {
                return ResourceManager.GetString("ConfirmDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm password is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmPwIsWrong {
            get {
                return ResourceManager.GetString("ConfirmPwIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection has been closed by server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnClosed {
            get {
                return ResourceManager.GetString("ConnClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully connected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConnectSuccess {
            get {
                return ResourceManager.GetString("ConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This object already used, so couldn&apos;t delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldntDelData {
            get {
                return ResourceManager.GetString("CouldntDelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The operator already underwent exam, so couldn&apos;t delete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldntDelOp {
            get {
                return ResourceManager.GetString("CouldntDelOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t open connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CouldntOpenConn {
            get {
                return ResourceManager.GetString("CouldntOpenConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataBaseError {
            get {
                return ResourceManager.GetString("DataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data may not be appropriate. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DataMayNotBeAppropriate {
            get {
                return ResourceManager.GetString("DataMayNotBeAppropriate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Department に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please determine gender. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetermineGender {
            get {
                return ResourceManager.GetString("DetermineGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosed Dr. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiagnosedDr {
            get {
                return ResourceManager.GetString("DiagnosedDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnoses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Diagnoses {
            get {
                return ResourceManager.GetString("Diagnoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnosis に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dianosis is required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiagnosisIsRequired {
            get {
                return ResourceManager.GetString("DiagnosisIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draft に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Duplicated {
            get {
                return ResourceManager.GetString("Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exam date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Examination Report に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExamReport {
            get {
                return ResourceManager.GetString("ExamReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exam(s) already exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExamsAlreadyExist {
            get {
                return ResourceManager.GetString("ExamsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exam type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExamType {
            get {
                return ResourceManager.GetString("ExamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel is needed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExcelNeeded {
            get {
                return ResourceManager.GetString("ExcelNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Female に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is being used. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileBeingUsed {
            get {
                return ResourceManager.GetString("FileBeingUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNotExist {
            get {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Findings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Findings {
            get {
                return ResourceManager.GetString("Findings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder is not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderNotExist {
            get {
                return ResourceManager.GetString("FolderNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You going to change patient ID. Do you really want to change Patient ID? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IDchanging {
            get {
                return ResourceManager.GetString("IDchanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This ID already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IdDuplicated {
            get {
                return ResourceManager.GetString("IdDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to log out? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InformLogout {
            get {
                return ResourceManager.GetString("InformLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location text is too long. (Max: 255 characters) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Location2Long {
            get {
                return ResourceManager.GetString("Location2Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock procedure failed. Call administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LockFailed {
            get {
                return ResourceManager.GetString("LockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Male に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please determine category. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoCategory {
            get {
                return ResourceManager.GetString("NoCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please determine department. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoDepartment {
            get {
                return ResourceManager.GetString("NoDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no diagnosis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoDiagnosis {
            get {
                return ResourceManager.GetString("NoDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No exam. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoExam {
            get {
                return ResourceManager.GetString("NoExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID is needed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoID {
            get {
                return ResourceManager.GetString("NoID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No is needed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoIsNeeded {
            get {
                return ResourceManager.GetString("NoIsNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name is needed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No operator found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoOperator {
            get {
                return ResourceManager.GetString("NoOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No out of range. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoOutOfRange {
            get {
                return ResourceManager.GetString("NoOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find patient data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoPatient {
            get {
                return ResourceManager.GetString("NoPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please determine password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoPw {
            get {
                return ResourceManager.GetString("NoPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No record. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Openning form was failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFormFailed {
            get {
                return ResourceManager.GetString("OpenFormFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ordered Dr. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OrderedDr {
            get {
                return ResourceManager.GetString("OrderedDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission denied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of place (Room name) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Place No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlaceNo {
            get {
                return ResourceManager.GetString("PlaceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plug-in couldn&apos;t get patient&apos;s name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PluginCouldntGetPtName {
            get {
                return ResourceManager.GetString("PluginCouldntGetPtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server port has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string portUnconfigured {
            get {
                return ResourceManager.GetString("portUnconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Procedure has been cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcedureCancelled {
            get {
                return ResourceManager.GetString("ProcedureCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ptName {
            get {
                return ResourceManager.GetString("ptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ptSelect {
            get {
                return ResourceManager.GetString("ptSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purpose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server password has been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pwConfigured {
            get {
                return ResourceManager.GetString("pwConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server password has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pwUnconfigured {
            get {
                return ResourceManager.GetString("pwUnconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission denied. Read only mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadOnlyMode {
            get {
                return ResourceManager.GetString("ReadOnlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveChangesYN {
            get {
                return ResourceManager.GetString("SaveChangesYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select protocol に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string selectProtocol {
            get {
                return ResourceManager.GetString("selectProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server IP has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file may be corrupt. Do you want to delete setting file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFileBroken {
            get {
                return ResourceManager.GetString("SettingFileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Side view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SideView {
            get {
                return ResourceManager.GetString("SideView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small-bowel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SmallBowel {
            get {
                return ResourceManager.GetString("SmallBowel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Software error occured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SoftwareError {
            get {
                return ResourceManager.GetString("SoftwareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s still draft. Continue? [To change this exam &quot;Diagnosed&quot;, click &quot;Diagnosed&quot; button.] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StillDraft {
            get {
                return ResourceManager.GetString("StillDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summary has changed. Do you want save it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SummarySaveYN {
            get {
                return ResourceManager.GetString("SummarySaveYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Suspect {
            get {
                return ResourceManager.GetString("Suspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protocol name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string t_categoryName {
            get {
                return ResourceManager.GetString("t_categoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateDone {
            get {
                return ResourceManager.GetString("UpdateDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Visible に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ward/Out patient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Ward {
            get {
                return ResourceManager.GetString("Ward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WrongConnectingString {
            get {
                return ResourceManager.GetString("WrongConnectingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong ID or Password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WrongIDorPW {
            get {
                return ResourceManager.GetString("WrongIDorPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can delete this row after update. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YouCanDelAfterUpdate {
            get {
                return ResourceManager.GetString("YouCanDelAfterUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can make changes only to pathology result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YouCanMakeChangesOnlyToPatho {
            get {
                return ResourceManager.GetString("YouCanMakeChangesOnlyToPatho", resourceCulture);
            }
        }
    }
}
