//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindingsEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindingsEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Age に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Birthday に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank/Draft(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BlankDraft {
            get {
                return ResourceManager.GetString("BlankDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Canceled(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Canceled_E {
            get {
                return ResourceManager.GetString("Canceled_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checked(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Colon {
            get {
                return ResourceManager.GetString("Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection closed by server. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionClosedByServer {
            get {
                return ResourceManager.GetString("ConnectionClosedByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection string is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionStringIsWrong {
            get {
                return ResourceManager.GetString("ConnectionStringIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection successful. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyToClipBoard {
            get {
                return ResourceManager.GetString("CopyToClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not establish connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotEstablishConnection {
            get {
                return ResourceManager.GetString("CouldNotEstablishConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find patient data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldNotFindPatientData {
            get {
                return ResourceManager.GetString("CouldNotFindPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Couldn&apos;t find patient data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CouldntFindPatientData {
            get {
                return ResourceManager.GetString("CouldntFindPatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DataBaseError {
            get {
                return ResourceManager.GetString("DataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database server IP address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DbServerIpAddress {
            get {
                return ResourceManager.GetString("DbServerIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database server port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DbSrvPort {
            get {
                return ResourceManager.GetString("DbSrvPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database user ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DbUserId {
            get {
                return ResourceManager.GetString("DbUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Database user password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DbUserPw {
            get {
                return ResourceManager.GetString("DbUserPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default findings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultFindings {
            get {
                return ResourceManager.GetString("DefaultFindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Department に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Departments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnoses に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Diagnoses {
            get {
                return ResourceManager.GetString("Diagnoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you really want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouReallyWantToDeleteIt {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you wish to log out? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWishToLogOut {
            get {
                return ResourceManager.GetString("DoYouWishToLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit patient information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditPatientInformation {
            get {
                return ResourceManager.GetString("EditPatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Equipments {
            get {
                return ResourceManager.GetString("Equipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExamDate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exam List に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExamList {
            get {
                return ResourceManager.GetString("ExamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exam record(s) already exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExamRecordAlreadyExist {
            get {
                return ResourceManager.GetString("ExamRecordAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExamType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExamType {
            get {
                return ResourceManager.GetString("ExamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   e.x. 192.168.1.10 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string exIP {
            get {
                return ResourceManager.GetString("exIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Female に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Figure folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FigureFolder {
            get {
                return ResourceManager.GetString("FigureFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File in use. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileInUse {
            get {
                return ResourceManager.GetString("FileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Findings Editor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FindingsEditor {
            get {
                return ResourceManager.GetString("FindingsEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderDoesNotExist {
            get {
                return ResourceManager.GetString("FolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gender に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdAlreadyExists {
            get {
                return ResourceManager.GetString("IdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID may not be changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdMayNotBeChanged {
            get {
                return ResourceManager.GetString("IdMayNotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID required. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IdRequired {
            get {
                return ResourceManager.GetString("IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InitialSettings {
            get {
                return ResourceManager.GetString("InitialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input your ID and Password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputYourIDandPassword {
            get {
                return ResourceManager.GetString("InputYourIDandPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock procedure failed. Please contact your administrator. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LockProcedureFailed {
            get {
                return ResourceManager.GetString("LockProcedureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Male に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Management に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   http://www.madeinclinic.co.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MicUrl {
            get {
                return ResourceManager.GetString("MicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My words に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MyWords {
            get {
                return ResourceManager.GetString("MyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New examination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewExamination {
            get {
                return ResourceManager.GetString("NewExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New patient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewPatient {
            get {
                return ResourceManager.GetString("NewPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No data found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No exam on record. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoExamOnRecord {
            get {
                return ResourceManager.GetString("NoExamOnRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No record. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not supported file type. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NotSupportedFileType {
            get {
                return ResourceManager.GetString("NotSupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ordered Dr.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OrderedDr {
            get {
                return ResourceManager.GetString("OrderedDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patient data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatientData {
            get {
                return ResourceManager.GetString("PatientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Patient ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission denied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PermissionDenied {
            get {
                return ResourceManager.GetString("PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Places (Rooms) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PlacesRooms {
            get {
                return ResourceManager.GetString("PlacesRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please determine password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PleaseDeterminPassword {
            get {
                return ResourceManager.GetString("PleaseDeterminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plug-in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin {
            get {
                return ResourceManager.GetString("Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plug-in couldn&apos;t get patient&apos;s name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PluginCouldntGetPtName {
            get {
                return ResourceManager.GetString("PluginCouldntGetPtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Procedure has been cancelled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProcedureHasBeenCancelled {
            get {
                return ResourceManager.GetString("ProcedureHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purpose に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password has been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PwHasBeenConfigured {
            get {
                return ResourceManager.GetString("PwHasBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PwHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("PwHasNotBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Permission denied. Read only mode. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReadOnlyMode {
            get {
                return ResourceManager.GetString("ReadOnlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Renew Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RenewPw {
            get {
                return ResourceManager.GetString("RenewPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save and Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by date に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchByDate {
            get {
                return ResourceManager.GetString("SearchByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by department に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchByDepartment {
            get {
                return ResourceManager.GetString("SearchByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by operator 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchByOp1 {
            get {
                return ResourceManager.GetString("SearchByOp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search by operator 1-5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchByOp15 {
            get {
                return ResourceManager.GetString("SearchByOp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search examination に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchExamination {
            get {
                return ResourceManager.GetString("SearchExamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search patient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SearchPatient {
            get {
                return ResourceManager.GetString("SearchPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select gender. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server IP has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServerIpHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("ServerIpHasNotBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server port has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServerPortHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("ServerPortHasNotBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server password has not been configured. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ServerPwHasNotBeenConfigured {
            get {
                return ResourceManager.GetString("ServerPwHasNotBeenConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The setting file may be corrupt. Do you want to delete the setting file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingFileCorrupt {
            get {
                return ResourceManager.GetString("SettingFileCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successfully updated. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Suspect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Suspect {
            get {
                return ResourceManager.GetString("Suspect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test connection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TestConnection {
            get {
                return ResourceManager.GetString("TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TheFileDoesNotExist {
            get {
                return ResourceManager.GetString("TheFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today&apos;s examinations に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TodaysExaminations {
            get {
                return ResourceManager.GetString("TodaysExaminations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View images に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ViewImages {
            get {
                return ResourceManager.GetString("ViewImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ward/Outpatient に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WardOutpatient {
            get {
                return ResourceManager.GetString("WardOutpatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wards に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Wards {
            get {
                return ResourceManager.GetString("Wards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Words に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong ID or Password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WrongIDorPW {
            get {
                return ResourceManager.GetString("WrongIDorPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can make changes only to pathology result. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YouCanMakeChangesOnlyToPatho {
            get {
                return ResourceManager.GetString("YouCanMakeChangesOnlyToPatho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You going to change patient ID. Do you really want to change Patient ID? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string YouGoingToChangePtId {
            get {
                return ResourceManager.GetString("YouGoingToChangePtId", resourceCulture);
            }
        }
    }
}
